// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20241121035615_addDbSet")]
    partial class addDbSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("WebApp.Models.tblOrder", b =>
                {
                    b.Property<int>("intOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dtOrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("intProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("numQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("strCustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("intOrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApp.Models.tblProduct", b =>
                {
                    b.Property<int>("intProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("numStock")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("numUnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("strProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("intProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApp.Models.TopCustomers", b =>
                {
                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stock")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerName");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
